// Generated by CoffeeScript 1.12.6
(function() {
  var dataFile, express, fs, hbs, path, router;

  express = require('express');

  router = express.Router();

  fs = require('fs');

  path = require('path');

  hbs = require('hbs');

  hbs.registerHelper('description', function() {
    console.log("what the fuck?");
    return this.data.description[this.curLang];
  });

  dataFile = path.join(process.env.MR_EXPRESS_ROOT, 'data/main.json');

  fs.readFile(dataFile, function(err, data) {
    var mainPage;
    if (err) {
      console.log("Could not read auth data from " + dataFile + ": " + err.code);
      throw err;
    }
    mainPage = JSON.parse(data + "");
    console.log(JSON.stringify(mainPage));
    return router.get('/', function(req, res, next) {
      var curLang, fbLang, forceLang, page, prefLang, ref, ref1, ref2;
      fbLang = req.get('X-Facebook-Locale');
      prefLang = (ref = (ref1 = req.acceptsLanguages('fr', 'en')) != null ? ref1 : fbLang) != null ? ref : 'en';
      page = req.query.page;
      if (page === "") {
        page = null;
      }
      forceLang = req.query.forceLang;
      if (forceLang === "") {
        forceLang = null;
      }
      curLang = (ref2 = forceLang != null ? forceLang : fbLang) != null ? ref2 : prefLang;
      res.render('index', {
        prefLang: prefLang,
        page: page,
        title: "marionrampal.com",
        curLang: curLang,
        forceLang: forceLang,
        data: mainPage
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
