// Generated by CoffeeScript 1.12.6
(function() {
  var express, hbs, mainPage, router;

  express = require('express');

  router = express.Router();

  hbs = require('hbs');

  mainPage = require('../data/main');

  hbs.registerHelper('description', function() {
    return this.data.description[this.curLang];
  });

  router.get('/', function(req, res, next) {
    var curLang, fbLang, forceLang, page, prefLang, ref, ref1, ref2;
    fbLang = req.get('X-Facebook-Locale');
    prefLang = (ref = (ref1 = req.acceptsLanguages('fr', 'en')) != null ? ref1 : fbLang) != null ? ref : 'en';
    page = req.query.page;
    if (page === "") {
      page = null;
    }
    forceLang = req.query.forceLang;
    if (forceLang === "") {
      forceLang = null;
    }
    curLang = (ref2 = forceLang != null ? forceLang : fbLang) != null ? ref2 : prefLang;
    res.render('index', {
      prefLang: prefLang,
      page: page,
      title: "marionrampal.com",
      curLang: curLang,
      forceLang: forceLang,
      data: mainPage
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
