// Generated by CoffeeScript 2.5.1
(function() {
  var express, hbs, log, onInit, router;

  express = require('express');

  router = express.Router();

  log = require('../helpers/logger').mainLogger;

  hbs = require('hbs');

  hbs.registerHelper('description', function() {
    return this.mainPage.description[this.curLang];
  });

  onInit = function(_, config) {
    log.info({config}, "configuration object");
    // GET home page. 
    return router.get('/', function(req, res, next) {
      var basePath, curLang, fbLang, forceLang, page, prefLang, ref, ref1, ref2;
      log = require('../helpers/logger').requestLogger(req);
      fbLang = req.get('X-Facebook-Locale');
      prefLang = (ref = (ref1 = req.acceptsLanguages('fr', 'en')) != null ? ref1 : fbLang) != null ? ref : 'en';
      basePath = req.query.path;
      basePath = (basePath != null ? basePath : '') + '/';
      log.info(basePath);
      page = req.query.page;
      if (page === "") {
        page = null;
      }
      forceLang = req.query.forceLang;
      if (forceLang === "") {
        forceLang = null;
      }
      curLang = (ref2 = forceLang != null ? forceLang : fbLang) != null ? ref2 : prefLang;
      res.render('index', {
        basePath: basePath,
        prefLang: prefLang,
        page: page,
        title: config.title,
        curLang: curLang,
        forceLang: forceLang,
        mainPage: config.mainPage
      });
    });
  };

  require('../helpers/init').readConfig(onInit);

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
